plugins {
    id 'com.android.library'
}

group 'com.gtbluesky.onnxruntime'
version '1.0'

android {
    namespace 'com.gtbluesky.onnxruntime'
    compileSdk 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdk 24
    }
}

dependencies {
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.30.0'
}

