"""Generate CMake 3.10-compatible constants from the pinned JSON manifest."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate(manifest):
    lines = ['# Generated by tool/generate_native_downloads.py; do not edit.']
    for archive in manifest['archives']:
        key = archive['target'].replace('-', '_')
        members = list(archive['files'].values())
        root = members[0].split('/')[0]
        values = {'URL': archive['url'], 'SHA256': archive['sha256'], 'ROOT': root}
        libraries = []
        hashes = []
        for destination, member in archive['files'].items():
            if destination in manifest['libraries']:
                libraries.append(member[len(root)+1:])
                hashes.append(manifest['libraries'][destination])
        values['LIBRARIES'] = ';'.join(libraries)
        values['HASHES'] = ';'.join(hashes)
        for name, value in values.items():
            lines.append(f'set(ORT_{key}_{name} "{value}")')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    manifest = json.loads((ROOT / 'tool/native_runtime_versions.json').read_text())
    (ROOT / 'cmake/onnxruntime_downloads.cmake').write_text(generate(manifest))
