include("${CMAKE_CURRENT_LIST_DIR}/onnxruntime_downloads.cmake")

# Verify extracted libraries too: a partially populated or modified cache must
# not silently change the runtime shipped by the plugin.
function(onnxruntime_check directory libraries hashes output)
  set(valid TRUE)
  list(LENGTH libraries count)
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    list(GET libraries ${index} name)
    list(GET hashes ${index} expected)
    if(NOT EXISTS "${directory}/${name}")
      set(valid FALSE)
      break()
    endif()
    file(SHA256 "${directory}/${name}" actual)
    if(NOT actual STREQUAL expected)
      set(valid FALSE)
      break()
    endif()
  endforeach()
  foreach(notice LICENSE ThirdPartyNotices.txt)
    if(NOT EXISTS "${directory}/${notice}")
      set(valid FALSE)
    endif()
  endforeach()
  set(${output} ${valid} PARENT_SCOPE)
endfunction()

function(onnxruntime_download target output)
  string(REPLACE "-" "_" key "${target}")
  if(NOT DEFINED ORT_${key}_URL)
    message(FATAL_ERROR "Unsupported ONNX Runtime download target: ${target}")
  endif()
  set(url "${ORT_${key}_URL}")
  set(sha "${ORT_${key}_SHA256}")
  set(root "${ORT_${key}_ROOT}")
  set(libraries "${ORT_${key}_LIBRARIES}")
  set(hashes "${ORT_${key}_HASHES}")
  if(NOT ORT_CACHE_DIR)
    if(DEFINED ENV{ORT_CACHE_DIR} AND NOT "$ENV{ORT_CACHE_DIR}" STREQUAL "")
      set(ORT_CACHE_DIR "$ENV{ORT_CACHE_DIR}")
    else()
      set(ORT_CACHE_DIR "${CMAKE_BINARY_DIR}/_deps/onnxruntime")
    endif()
  endif()
  get_filename_component(cache "${ORT_CACHE_DIR}" ABSOLUTE)
  set(entry "${cache}/${sha}")
  file(MAKE_DIRECTORY "${entry}")
  # Serialize download/extraction across concurrent builds sharing the cache.
  file(LOCK "${entry}/download.lock" GUARD FUNCTION TIMEOUT 600)
  set(directory "${entry}/${root}")
  onnxruntime_check("${directory}" "${libraries}" "${hashes}" valid)
  if(NOT valid)
    set(archive "${entry}/archive")
    if(EXISTS "${archive}")
      file(SHA256 "${archive}" actual)
      if(NOT actual STREQUAL sha)
        message(FATAL_ERROR "ONNX Runtime cached archive checksum mismatch: ${archive}. Remove this file and retry.")
      endif()
    else()
      message(STATUS "Downloading ONNX Runtime ${target}: ${url}")
      file(DOWNLOAD "${url}" "${archive}.part" STATUS status
        TLS_VERIFY ON TIMEOUT 600 INACTIVITY_TIMEOUT 60)
      list(GET status 0 code)
      if(NOT code EQUAL 0)
        file(REMOVE "${archive}.part")
        message(FATAL_ERROR "ONNX Runtime download failed: ${status}. Check network/proxy settings or prefill ORT_CACHE_DIR.")
      endif()
      file(SHA256 "${archive}.part" actual)
      if(NOT actual STREQUAL sha)
        file(REMOVE "${archive}.part")
        message(FATAL_ERROR "ONNX Runtime archive checksum mismatch for ${url}")
      endif()
      file(RENAME "${archive}.part" "${archive}")
    endif()
    set(stage "${entry}/extracting")
    file(REMOVE_RECURSE "${stage}")
    file(MAKE_DIRECTORY "${stage}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf "${archive}"
      WORKING_DIRECTORY "${stage}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Could not extract ONNX Runtime archive: ${archive}")
    endif()
    onnxruntime_check("${stage}/${root}" "${libraries}" "${hashes}" valid)
    if(NOT valid)
      message(FATAL_ERROR "ONNX Runtime extracted library checksum mismatch: ${archive}")
    endif()
    file(REMOVE_RECURSE "${directory}")
    file(RENAME "${stage}/${root}" "${directory}")
    file(REMOVE_RECURSE "${stage}")
  endif()
  set(${output} "${directory}" PARENT_SCOPE)
endfunction()
