# Flutter supplies the target platform even when cross-compiling. Older builds
# can fall back to the generator platform (MSVC) or target system processor.
function(onnxruntime_target_arch platform output)
  if(DEFINED FLUTTER_TARGET_PLATFORM AND NOT FLUTTER_TARGET_PLATFORM STREQUAL "")
    if(FLUTTER_TARGET_PLATFORM STREQUAL "${platform}-arm64")
      set(arch arm64)
    elseif(FLUTTER_TARGET_PLATFORM STREQUAL "${platform}-x64")
      set(arch x64)
    else()
      message(FATAL_ERROR "Unsupported ONNX Runtime target: ${FLUTTER_TARGET_PLATFORM}")
    endif()
  else()
    if(platform STREQUAL "windows" AND NOT CMAKE_GENERATOR_PLATFORM STREQUAL "")
      string(TOLOWER "${CMAKE_GENERATOR_PLATFORM}" processor)
    else()
      string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" processor)
    endif()
    if(processor MATCHES "^(arm64|aarch64)$")
      set(arch arm64)
    elseif(processor MATCHES "^(x64|x86_64|amd64)$")
      set(arch x64)
    else()
      message(FATAL_ERROR "Unsupported ONNX Runtime architecture: ${processor}")
    endif()
  endif()
  set(${output} "${arch}" PARENT_SCOPE)
endfunction()
